
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 12 12:06:13 CDT 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Char = 3;
  public static final int Numero = 11;
  public static final int Sin_Regreso = 9;
  public static final int Float = 4;
  public static final int Llave_CR = 16;
  public static final int ERROR = 12;
  public static final int Identificador = 10;
  public static final int Int = 2;
  public static final int Coma = 17;
  public static final int Double = 5;
  public static final int Parentesis_CR = 14;
  public static final int Cadena = 6;
  public static final int EOF = 0;
  public static final int Llave_AP = 15;
  public static final int Private = 8;
  public static final int Publico = 7;
  public static final int error = 1;
  public static final int Parentesis_AP = 13;
}

